Adjust entrypoint setup
EnvelopSound/Earshot pull request #19
Opened 2021-04-04 02:01 UTC by nadirhamid

This PR adds to the existing SSL checks in entrypoint.sh. I have added environment variable SSL_ENABLED which will let users switch SSL setting on and off. This patch is useful to any user who may not want to deploy in SSL mode.

2021-04-05 21:34 UTC, roddylindsay requested changes

2021-04-05 21:34 UTC, roddylindsay commented on templates/cloudformation-template.yaml
>    AccessKey:
can these be blank by default and dynamically required based on another flag HTTPSIsEnabled in the template (disabled by default)?

2021-04-05 21:34 UTC, roddylindsay commented on templates/cloudformation-template.yaml
> +                 Image: envelopsound/earshot:v0.2
why is this in here?

2021-04-05 21:35 UTC, roddylindsay commented on templates/cloudformation-template.yaml
>    AccessKey:
also, these need to be applied to the other templates as well

2021-04-18 18:53 UTC, nadirhamid commented
@roddylindsay  Updates made as suggested. I have updated the CF stack and the documentation. Please have a look.

Thanks

2021-04-27 05:05 UTC, roddylindsay approved these changes

2021-04-27 05:05 UTC, merged